version: "3"
services:
  nydoz_frontend:
    container_name: nydoz_frontend_separate
    build:
      context: ./docker/runtimes/19
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:9000:5174'
    volumes:
      - '.:/var/www/nydoz-react/'
      # - '../apps/backend/docker/runtimes/8.2/nginx/sites-enabled:/etc/nginx/sites-enabled'
    networks:
      - nydoz
    tty: true
networks:
  nydoz:
    driver: bridge