export const dailyQuotes = [
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
];
