import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState, useRef } from "react";
// import { useNavigate } from "react-router-dom";
import useAuthContext from "../../../../../context/auth/useAuthContext";
import { NavLink } from "react-router-dom";
import MyProducts from "./MyProducts";
import { useOnClickOutside } from "usehooks-ts";
import NavDropdown from "react-bootstrap/NavDropdown";
import { LinkContainer } from "react-router-bootstrap";
import { BuildingAdd } from "react-bootstrap-icons";
import UserCompanyAndProducts from "./products/UserCompanyAndProducts";
import Images from "../../../../../constants/Images";
import AllPublicProductsDropdown from "./products/AllPublicProductsDropdown";
import { RiLockPasswordFill, RiLogoutBoxRLine } from "react-icons/ri";
import { BsBuildingAdd } from "react-icons/bs";
import APP_SETTING from "../../../../../config/AppSetting";
const Navbar = () => {
    const productRef = useRef(null);
    const { isLoggedIn, dispatch } = useAuthContext();
    useOnClickOutside(productRef, () => setShowProducts(false));
    const [showProducts, setShowProducts] = useState(false);
    const logoutFn = () => {
        // localStorage.removeItem("token");
        // localStorage.removeItem("rememberMe");
        localStorage.clear();
        dispatch({ type: "LOGOUT" });
        window.location.href = APP_SETTING.APP_BASE_URL + "/auth/login";
    };
    return (_jsx("nav", { className: " navbar navbar-expand-lg bg-body-tertiary navbar-wrapper bg-white fixed-top ", children: _jsx("div", { className: "md:tw-w-11/12 lg:tw-w-11/12 xl:tw-w-9/12 sm:tw-w-11/12 xsm:tw-w-11/12  tw-mx-auto", children: _jsxs("div", { className: "inner-container  ", children: [_jsxs("div", { className: "left-container", children: [_jsx(NavLink, { className: "navbar-brand", to: "/", children: _jsx("img", { className: "navbar-brand-img ", src: Images.CompanyLogo, alt: "Company Logo" }) }), _jsxs("div", { ref: productRef, className: "p-relative", children: [_jsx("div", { className: "nav-item xsm:tw-hidden sm:tw-block ", children: _jsxs("div", { className: "d-flex align-items-center  btn btn-light-primary  btn-sm ", onClick: () => setShowProducts(() => !showProducts), children: [_jsx("i", { className: "ki-outline ki-abstract-26 fs-1 me-3 " }), _jsxs("span", { className: "fw-bold fs-7", children: ["Products & Services", _jsx("i", { className: "fas fa-chevron-down ms-2" })] })] }) }), _jsx("div", { children: _jsx(MyProducts, { showProduct: showProducts, children: isLoggedIn ? (_jsx(UserCompanyAndProducts, {})) : (_jsx(AllPublicProductsDropdown, {})) }) })] })] }), _jsx("div", { className: "right-container tw-absolute tw-right-3 -tw-bottom-2 ", children: isLoggedIn ? (_jsxs(_Fragment, { children: [_jsx("a", { className: "cursor-pointer me-2", href: APP_SETTING.APP_BASE_URL, children: _jsxs("div", { className: "tw-flex tw-flex-row tw-items-center  ", children: [_jsx("p", { className: "me-3", children: _jsx(BuildingAdd, { size: 16, color: "#1e40d6" }) }), _jsx("p", { className: "tw-self-end", children: "Workspace" })] }) }), _jsxs(NavDropdown, { title: "My Account", id: "nav-dropdown", children: [_jsx(NavDropdown.Item, { children: _jsx(LinkContainer, { className: "btn  btn-sm", to: "create-company", children: _jsxs("div", { className: "tw-flex gap-3", children: [_jsx(BsBuildingAdd, { size: 16, color: "black" }), _jsx("p", { className: "tw-w-full tw-text-gray-600", children: "Create New Company" })] }) }) }), _jsx(NavDropdown.Item, { children: _jsx(LinkContainer, { className: "btn  btn-sm w-100", to: "change-password", children: _jsxs("div", { className: "tw-flex gap-3", children: [_jsx(RiLockPasswordFill, { size: 16, color: "black" }), _jsx("p", { className: "tw-text-gray-600", children: "Change Password" })] }) }) }), _jsx(NavDropdown.Item, { children: _jsx("div", { className: "text-center", children: _jsxs("div", { className: "btn  btn-sm w-100 tw-flex gap-3", onClick: () => logoutFn(), children: [_jsx(RiLogoutBoxRLine, { size: 16, color: "#0b0b0b" }), _jsx("p", { className: "me-3 tw-text-gray-600", children: "Logout" })] }) }) })] })] })) : (_jsx("div", { children: _jsx(NavLink, { className: "nav-link fw-bold ", to: "/auth/login", children: "Login" }) })) })] }) }) }));
};
export default Navbar;
