#!/usr/bin/env bash
if [[ ! -f "/var/www/nydoz-angular" ]]; then
  cd /var/www/nydoz-angular && npm install
fi
ng serve --host=0.0.0.0 --port=80 --disable-host-check

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER laravel-10-developer
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
