import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { RESULT_PER_PAGE_LIST } from "../../../constants/AppSetting";
const Pagination = (props) => {
    const { pagination, handlePrevious, handleNext, handlePerPageChange } = props;
    return (_jsxs("div", { className: 'row my-3', children: [_jsxs("div", { className: 'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-start', children: [_jsx("label", { className: ' me-3', children: "Result Per page" }), _jsx("div", { className: 'd-flex justify-content-between  align-items-center', children: _jsx("select", { value: pagination?.per_page || 20, onChange: handlePerPageChange, name: 'kt_customers_table_length', "aria-controls": 'kt_customers_table', className: ' form-select form-select-sm form-select-solid', children: RESULT_PER_PAGE_LIST.map((item, index) => (_jsx("option", { value: item, children: item }, index))) }) })] }), _jsx("div", { className: 'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-end', children: _jsx("div", { className: 'dataTables_paginate paging_simple_numbers', id: 'kt_customers_table_paginate', children: _jsxs("ul", { className: 'pagination', children: [_jsx("li", { onClick: handlePrevious, className: pagination.current_page === 1
                                    ? "paginate_button page-item disabled"
                                    : "paginate_button page-item", id: 'kt_customers_table_previous', children: _jsxs("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '0', className: 'page-link', children: [_jsx("i", { className: 'previous' }), _jsx("span", { className: 'ms-3', children: "Prev" })] }) }), _jsx("li", { className: 'paginate_button page-item active', children: _jsx("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '1', className: 'page-link', children: "1" }) }), _jsx("li", { className: 'paginate_button page-item ', children: _jsx("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '2', className: 'page-link', children: "2" }) }), _jsx("li", { className: 'paginate_button page-item ', children: _jsx("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '3', className: 'page-link', children: "3" }) }), _jsx("li", { className: 'paginate_button page-item ', children: _jsx("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '4', className: 'page-link', children: "4" }) }), _jsx("li", { onClick: handleNext, className: 'paginate_button page-item next', id: 'kt_customers_table_next', children: _jsxs("a", { href: '#', "aria-controls": 'kt_customers_table', "data-dt-idx": '5', className: 'page-link me-3', children: ["Next", _jsx("i", { className: 'next' })] }) })] }) }) })] }));
};
export default Pagination;
